### ISSUE TITLE
TEA => Content Issues in High School Statistics

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#314]
# Scenario

This issue collects the various Content issues encountered in TEA High School Statistics. Individual issues can be spun off as necessary.

# Reproducibility Details

- **Impact area**: Gateway Staging
- **User**: openstax@texasgateway.org
- **URL / Location**: stg.texasgateway.org
- **How many times were you able to reproduce the issue?** n/a

## Screenshots
1. 
![image](https://user-images.githubusercontent.com/12678235/29420312-3ab9c9f8-8337-11e7-9440-22d96726fea2.png)
**[Ch. 1.1 ](https://stg.texasgateway.org/resource/11-definitions-statistics-probability-and-key-terms?book=261661)-- "Exercise" is misspelled in content**
**Bookwide -- semicolons are missing.** (Note: also missing in the epub. But, [here](https://stg.texasgateway.org/resource/21-stem-and-leaf-graphs-stemplots-line-graphs-and-bar-graphs) is an example from Ch. 2.1 of semicolons that look OK.)

**2017-09-12 Status:** ✅ 

2. 
![image](https://user-images.githubusercontent.com/12678235/29421487-dc47ab70-833a-11e7-89ef-baf021384ab5.png)
**[Section 1.2](https://stg.texasgateway.org/resource/12-data-sampling-and-variation-data-and-sampling?book=261661) -- Floating period in "Marginal Distributions in Two-Way Tables" section** (also found in [section 3.1](https://tea.cnx.org/contents/sSWElGPd@5.197:iOJzdc1t@5/31-Terminology), search for `If you were to roll the die only a few times`)

**2017-09-12 Status:** ✅

3. 
![image](https://user-images.githubusercontent.com/11298165/30185954-34b558f2-93e9-11e7-9756-620d8fd5a56c.png)
**[Section 1.3](https://stg.texasgateway.org/resource/13-frequency-frequency-tables-and-levels-measurement?book=278536) -- It looks like solution 1.17d should be "87 percent" but it's just "87"**

**2017-09-12 Status:** ⚠️ 

4. 
![image](https://user-images.githubusercontent.com/11298165/29428811-27c3c23c-8354-11e7-9ff7-f797cb0a9dab.png)
**[Section 2.4](https://stg.texasgateway.org/resource/24-box-plots?book=261661&binder_id=) -- possible fragment in Solution 2.25.**

**2017-09-12 Status:** ✅ 

5. 
![image](https://user-images.githubusercontent.com/11298165/29429324-eb142064-8355-11e7-93d1-227b8904dd12.png)
**[Section 2.6](https://stg.texasgateway.org/resource/26-skewness-and-mean-median-and-mode) -- missing image for Figure 2.25**

**2017-09-12 Status:** ✅ 

6. 
![image](https://user-images.githubusercontent.com/11298165/29434722-da804142-8369-11e7-9cc6-bb284f63291e.png)
**[Section 3.5](https://tea.cnx.org/contents/sSWElGPd@5.197:kjlYB7HQ@5/35-Tree-and-Venn-Diagrams) -- missing image for Solution 3.24e**

**2017-09-12 Status:** ✅ 

7. 
![image](https://user-images.githubusercontent.com/12678235/29442068-fca618c0-8394-11e7-8c6a-09276a873b1f.png)
**[High School Statistics Appendix H](https://stg.texasgateway.org/resource/h-tables?book=261661&binder_id=261656) -- Titles missing, and content after "going to" on the All four tables... line**

**2017-09-12 Status:** ✅  

# Environment:

- **OS**: macOS
- **Browser**: Chrome

**Comment by helenemccarron** [comment]
- Typo fixed in PR #297 
- `;` pending discussion tomorrow
- Other screenshots: Ryan is fixing content

**Comment by helenemccarron** [comment]
The `;` are added via CSS. We need to remove them from the CSS on webview and add them in the recipes

**Comment by oscryan** [comment]
Floating periods fixed on tea.cnx.org, email out to WW for fragment solution, all images now present on tea.cnx.org, and the Appendix H titles issue is not a content problem (those are list titles).

**Comment by oscryan** [comment]
Got content from ww and fixed the Ms Park's fragment

**Comment by Stackblocks** [comment]
Still seeing the missing image in 2.6 (No. 4) and the content is still missing from the end of `All four tables can be accessed by going to` in Table H, but the rest are resolved.

![image](https://user-images.githubusercontent.com/12678235/29633865-4f3108da-880d-11e7-8211-5c490f50afb4.png)
![image](https://user-images.githubusercontent.com/12678235/29633870-528d43b8-880d-11e7-8a5d-e9ec465ad78d.png)

**Comment by Stackblocks** [comment]
Table H issue resolved by Ryan.

**Comment by oscryan** [comment]
@helenemccarron @philschatz that missing image in section 2.6 is for sure there on both tea.cnx.org and in the epub, it's just not getting pulled into the content. wasn't there something like this before?

**Comment by helenemccarron** [comment]
@oscryan I think it's broken in webview and the PDF. It looks like the `img` tag isn't opened properly.
![2017-08-25_16-24-31](https://user-images.githubusercontent.com/8514591/29733274-0059e712-89b2-11e7-9f19-cc7a1ec500db.png)
![2017-08-25_16-03-05](https://user-images.githubusercontent.com/8514591/29733292-1860f88c-89b2-11e7-81a5-fc761ec55865.png)

**Comment by kerwinso** [comment]
Missing image in 2.6 was verified fixed in this test collection: https://qa.cnx.org/contents/JGFFI57s@1.1:4GnZv-ko@1/11-Skewness-and-the-Mean-Media (look for Figure 1.8)
